@startuml

class ProductTemplate {
  Long dbId
  String id
  String categoryName
  List<ConfigurableField>
}

class ConfigurableField {
  Long dbId
  String id
  String fieldName
  String fieldType
  int fieldLength
  ProductCategory productCategory
}

enum fieldType {
    String
    Integer
    Float
}

ProductTemplate "1" - "n" ConfigurableField
ConfigurableField "1" - "1" fieldType

@enduml
